### ISSUE TITLE
[draft 02] "events" field minimum requirements

### ISSUE THREAD

**Issue by JorisHerbots** [quicwg/qlog#150] opened 2021-04-14 21:20 UTC
**Issue**
The specification mentions the following under the "Field name semantics" section (ID: field-name-semantics): 

> Each qlog event at minimum requires the "time" ({{time-based-fields}}), "name" ({{name-field}}) and "data" ({{data-field}}) fields.

According to the section "category and event" (ID: name-field), `name` is the concatenation of the `category` and `type` fields. This should be reflected in the line above.

**Suggestion**
> Each qlog event at minimum requires the "time" ({{time-based-fields}}), "name" (or "category" and "type") ({{name-field}}) and "data" ({{data-field}}) fields.

**Comment by rmarx** [comment] 2021-04-15 08:29
So this is a bit of a difficult one... As explained in section `name-field`, category+type were used in qlog draft 01 but in 02 it's preferred to use the concatenated version: `As such, the default approach in qlog is to concatenate both field values`

It's highly uncertain at this point how/if these fields will continue to exist in this form (see also #146, which means we might go to quic:packet_sent instead of transport:packet_sent in time for example).

So for now, I'd like to keep the text as-is (encourage concatenated form). 

Note: qvis -should- still support both category + event for draft02 for easier backwards compat though. If that's not the case, then that should be fixed.

**Comment by rmarx** [comment] 2021-08-18 13:46
Duplicate of #153, closing in favor of that.

**Closed by rmarx** 2021-08-18 13:46 UTC
Labels: design, high-level-schema, current-version, discuss
