### ISSUE TITLE
Improve connectivity:connection_id_updated

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#367] opened 2024-01-19 10:57 UTC
As reported by @hlandau on the mailing list:

connectivity:connection_id_updated:

  It would be nice to be able to optionally log CID-associated sequence
  numbers and the type of CID source (ODCID, Initial CID,
  preferred_address transport parameter, NCID frame, etc.)

**Comment by LPardue** [comment] 2024-01-24 01:26
Dupe of #373 that has discussion, so closing.

**Closed by LPardue** 2024-01-24 01:26 UTC
